### ISSUE TITLE
VGA signal

### ISSUE THREAD

**Issue by Dinth** [spark2k06/Universal-ITX-Backplane#1]
Hi. I hope you are well and thanks for designing such an amazing project!
If the board is still being developed, could i suggest adding an option to feed the VGA signal to the board using standard 2.54mm pins instead of DB-15 port? Many PC/104 boards with built in VGA have VGA output on pins instead of DB15 ports, so it would be much easier to connect that signal to the board using standard cables with 2.54mm connectors instead of making a custom 2.54mm to VGA cable

**Comment by spark2k06** [comment]
Hi, thanks!


I no longer continue with the development of it ... but the VGA connector called **VGA IN (PC/104)** may help you for your proposal:

![image](https://user-images.githubusercontent.com/3509674/148653633-a1199c0b-b367-4ba0-8a92-4b9c1a3946bf.png)
